### 1 : Importing Libraries

In [50]:
# ignore the warnings in the output
import warnings
warnings.filterwarnings("ignore")

import os
import sys
module_path = os.path.abspath(os.path.join('..'))
print(module_path)
if module_path not in sys.path:
    sys.path.append(module_path+"/scripts")
    print(sys.path)

/home/Assignment/02_training_pipeline
['/home/Assignment/02_training_pipeline/notebooks', '/opt/conda/lib/python3.8/site-packages/git/ext/gitdb', '/opt/conda/lib/python38.zip', '/opt/conda/lib/python3.8', '/opt/conda/lib/python3.8/lib-dynload', '', '/opt/conda/lib/python3.8/site-packages', '/home/Assignment/02_training_pipeline/scripts', '/home/Assignment/02_training_pipeline/scripts', '/home/Assignment/02_training_pipeline/scripts', '/opt/conda/lib/python3.8/site-packages/gitdb/ext/smmap', '/home/Assignment/02_training_pipeline/scripts']

In [51]:
# import libraries and packages
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import mlflow
from pycaret.classification import *
import utils

 ### 2 Reading Data

In [52]:
##Copy the cleaned data obtained from the data_cleaning notebook into the Data folder before proceeding
%time
dataset = pd.read_csv('Data/cleaned_data.csv')

CPU times: user 8 µs, sys: 0 ns, total: 8 µs
Wall time: 23.8 µs

In [53]:
dataset.head()

,created_date,city_tier,first_platform_c,first_utm_medium_c,first_utm_source_c,total_leads_droppped,referred_lead,app_complete_flag,assistance_interaction,career_interaction,payment_interaction,social_interaction,syllabus_interaction
0,2021-07-01 00:08:15,1.0,Level0,Level11,Level2,1.0,0.0,1,0.0,0.0,0.0,0.0,0.0
1,2021-07-01 00:16:43,2.0,Level3,Level0,others,1.0,0.0,1,0.0,0.0,0.0,0.0,0.0
2,2021-07-01 00:22:20,1.0,Level3,Level0,Level0,1.0,0.0,1,0.0,0.0,0.0,0.0,0.0
3,2021-07-01 00:23:13,1.0,Level1,Level3,others,2.0,0.0,0,0.0,0.0,0.0,0.0,0.0
4,2021-07-01 00:28:38,1.0,Level3,Level0,Level0,1.0,0.0,0,0.0,0.0,0.0,0.0,0.0

In [54]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 238970 entries, 0 to 238969
Data columns (total 13 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   created_date            238970 non-null  object
 1   city_tier               238970 non-null  float64
 2   first_platform_c        238970 non-null  object
 3   first_utm_medium_c      238970 non-null  object
 4   first_utm_source_c      238970 non-null  object
 5   total_leads_droppped    238970 non-null  float64
 6   referred_lead           238970 non-null  float64
 7   app_complete_flag       238970 non-null  int64
 8   assistance_interaction  238970 non-null  float64
 9   career_interaction      238970 non-null  float64
 10  payment_interaction     238970 non-null  float64
 11  social_interaction      238970 non-null  float64
 12  syllabus_interaction    238970 non-null  float64
dtypes: float64(8), int64(1), object(4)
memory usage: 23.7+ MB

In [55]:
dataset['first_utm_medium_c'].nunique()

45

In [56]:
dataset

,created_date,city_tier,first_platform_c,first_utm_medium_c,first_utm_source_c,total_leads_droppped,referred_lead,app_complete_flag,assistance_interaction,career_interaction,payment_interaction,social_interaction,syllabus_interaction
0,2021-07-01 00:08:15,1.0,Level0,Level11,Level2,1.0,0.0,1,0.0,0.0,0.0,0.0,0.0
1,2021-07-01 00:16:43,2.0,Level3,Level0,others,1.0,0.0,1,0.0,0.0,0.0,0.0,0.0
2,2021-07-01 00:22:20,1.0,Level3,Level0,Level0,1.0,0.0,1,0.0,0.0,0.0,0.0,0.0
3,2021-07-01 00:23:13,1.0,Level1,Level3,others,2.0,0.0,0,0.0,0.0,0.0,0.0,0.0
4,2021-07-01 00:28:38,1.0,Level3,Level0,Level0,1.0,0.0,0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
238965,2022-02-14 08:39:27,1.0,Level3,Level0,Level0,1.0,0.0,1,0.0,0.0,0.0,0.0,0.0
238966,2022-02-14 08:41:50,1.0,Level7,Level11,Level2,2.0,0.0,1,0.0,0.0,0.0,0.0,0.0
238967,2022-02-14 08:43:07,2.0,Level0,Level4,Level2,2.0,0.0,1,0.0,0.0,0.0,0.0,0.0
238968,2022-02-14 08:44:20,2.0,Level0,Level6,Level7,3.0,0.0,1,0.0,0.0,0.0,0.0,0.0
238969,2022-02-14 08:45:40,1.0,Level12,Level0,Level0,1.0,0.0,1,0.0,0.0,0.0,0.0,0.0

In [57]:
# drop the data column as it is not needed for training
dataset = dataset.drop(['created_date'], axis=1)

In [58]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 238970 entries, 0 to 238969
Data columns (total 12 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   city_tier               238970 non-null  float64
 1   first_platform_c        238970 non-null  object
 2   first_utm_medium_c      238970 non-null  object
 3   first_utm_source_c      238970 non-null  object
 4   total_leads_droppped    238970 non-null  float64
 5   referred_lead           238970 non-null  float64
 6   app_complete_flag       238970 non-null  int64
 7   assistance_interaction  238970 non-null  float64
 8   career_interaction      238970 non-null  float64
 9   payment_interaction     238970 non-null  float64
 10  social_interaction      238970 non-null  float64
 11  syllabus_interaction    238970 non-null  float64
dtypes: float64(8), int64(1), object(3)
memory usage: 21.9+ MB

In [59]:
data_for_model, data_unseen = utils.get_validation_unseen_set(dataset, validation_frac=0.05, sample=False, sample_frac=0.1)
print('Data for Modeling: ' + str(data_for_model.shape))
print('Unseen Data For Predictions: ' + str(data_unseen.shape))

Data for Modeling: (227022, 12)
Unseen Data For Predictions: (11948, 12)

### 3 Setting up Environment:

In [60]:
# create a connection and setup a SQLite database with the name "lead_scoring_model_experimentation.db" in 
# 'Assignment/02_training_pipeline/notebooks/' location

In [61]:
'''
Now you need to start the MLflow server in a new terminal. 
Note: Before you start the MLflow server, create a folder named mlruns in the assignment directory.
Now you need to run the command to start MLflow server such that:
1. The lead_scoring_model_experimentation.db which you created above is used as the backend-store.
2. mlruns folder is used as an artifact directory. 
3. The server runs on the port 6006.

The steps to do so are as follows:
Open a new terminal.
Then go to the Assignment directory using the cd command. Type the command: cd Assignment/
Create a folder named mlruns here. You can create this folder using either the command line or GUI. To create this folder via the command line run the command: mkdir ./mlruns
Then, type the following command to start the MLflow server: 
mlflow server --backend-store-uri='sqlite:///./02_training_pipeline/notebooks/lead_scoring_model_experimentation.db' --default-artifact-root="./mlruns" --port=6006 --host=0.0.0.0
'''

'\nNow you need to start the MLflow server in a new terminal. \nNote: Before you start the MLflow server, create a folder named mlruns in the assignment directory.\nNow you need to run the command to start MLflow server such that:\n1. The lead_scoring_model_experimentation.db which you created above is used as the backend-store.\n2. mlruns folder is used as an artifact directory. \n3. The server runs on the port 6006.\n\nThe steps to do so are as follows:\nOpen a new terminal.\nThen go to the Assignment directory using the cd command. Type the command: cd Assignment/\nCreate a folder named mlruns here. You can create this folder using either the command line or GUI. To create this folder via the command line run the command: mkdir ./mlruns\nThen, type the following command to start the MLflow server: \nmlflow server --backend-store-uri=\'sqlite:///./02_training_pipeline/notebooks/lead_scoring_model_experimentation.db\' --default-artifact-root="./mlruns" --port=6006 --host=0.0.0.0\n'

In [66]:
# Once, your server is successfully running, create a mlflow tracking uri at "http://0.0.0.0:6006"
mlflow.set_tracking_uri("http://0.0.0.0:6008")

In [67]:
Lead_scoring_mlflow_production = setup(data = data_for_model, target = 'app_complete_flag', 
                   session_id = 42,fix_imbalance=False,
                   n_jobs=-1,use_gpu=True,
                   log_experiment=True,experiment_name='Lead_scoring_mlflow_production',
                   log_plots=True, log_data=True,
                   silent=True, verbose=True,
                   log_profile=False)

2024/02/06 12:16:59 INFO mlflow.tracking.fluent: Experiment with name 'Lead_scoring_mlflow_production' does not exist. Creating a new experiment.

### 4 : Model Experimentation with pycaret

In [68]:
# create a experimentation with pycaret and exclude ['gbc','knn','qda', 'dummy', 'svm', 'ada']
excluded_models = ['gbc', 'knn', 'qda', 'dummy', 'svm', 'ada']
best_model = compare_models(fold = 5, exclude=excluded_models)

In [69]:
# create a model which gives the highest accuracy
lgbm  = create_model('lightgbm')

In [71]:
lgbm

LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               device='gpu', importance_type='split', learning_rate=0.1,
               max_depth=-1, min_child_samples=20, min_child_weight=0.001,
               min_split_gain=0.0, n_estimators=100, n_jobs=-1, num_leaves=31,
               objective=None, random_state=42, reg_alpha=0.0, reg_lambda=0.0,
               silent='warn', subsample=1.0, subsample_for_bin=200000,
               subsample_freq=0)

In [70]:
lgbm.feature_name_

['city_tier',
 'total_leads_droppped',
 'assistance_interaction',
 'career_interaction',
 'payment_interaction',
 'social_interaction',
 'syllabus_interaction',
 'first_platform_c_Level0',
 'first_platform_c_Level1',
 'first_platform_c_Level10',
 'first_platform_c_Level11',
 'first_platform_c_Level12',
 'first_platform_c_Level13',
 'first_platform_c_Level14',
 'first_platform_c_Level15',
 'first_platform_c_Level16',
 'first_platform_c_Level17',
 'first_platform_c_Level18',
 'first_platform_c_Level19',
 'first_platform_c_Level2',
 'first_platform_c_Level20',
 'first_platform_c_Level21',
 'first_platform_c_Level22',
 'first_platform_c_Level23',
 'first_platform_c_Level24',
 'first_platform_c_Level25',
 'first_platform_c_Level26',
 'first_platform_c_Level27',
 'first_platform_c_Level28',
 'first_platform_c_Level29',
 'first_platform_c_Level3',
 'first_platform_c_Level30',
 'first_platform_c_Level31',
 'first_platform_c_Level32',
 'first_platform_c_Level33',
 'first_platform_c_Level34',
 'first_platform_c_Level35',
 'first_platform_c_Level36',
 'first_platform_c_Level37',
 'first_platform_c_Level38',
 'first_platform_c_Level39',
 'first_platform_c_Level4',
 'first_platform_c_Level40',
 'first_platform_c_Level41',
 'first_platform_c_Level45',
 'first_platform_c_Level46',
 'first_platform_c_Level47',
 'first_platform_c_Level5',
 'first_platform_c_Level6',
 'first_platform_c_Level7',
 'first_platform_c_Level8',
 'first_platform_c_Level9',
 'first_utm_medium_c_Level0',
 'first_utm_medium_c_Level1',
 'first_utm_medium_c_Level10',
 'first_utm_medium_c_Level11',
 'first_utm_medium_c_Level12',
 'first_utm_medium_c_Level13',
 'first_utm_medium_c_Level14',
 'first_utm_medium_c_Level15',
 'first_utm_medium_c_Level16',
 'first_utm_medium_c_Level18',
 'first_utm_medium_c_Level19',
 'first_utm_medium_c_Level2',
 'first_utm_medium_c_Level20',
 'first_utm_medium_c_Level21',
 'first_utm_medium_c_Level22',
 'first_utm_medium_c_Level23',
 'first_utm_medium_c_Level24',
 'first_utm_medium_c_Level25',
 'first_utm_medium_c_Level26',
 'first_utm_medium_c_Level27',
 'first_utm_medium_c_Level28',
 'first_utm_medium_c_Level29',
 'first_utm_medium_c_Level3',
 'first_utm_medium_c_Level31',
 'first_utm_medium_c_Level32',
 'first_utm_medium_c_Level33',
 'first_utm_medium_c_Level34',
 'first_utm_medium_c_Level35',
 'first_utm_medium_c_Level36',
 'first_utm_medium_c_Level37',
 'first_utm_medium_c_Level38',
 'first_utm_medium_c_Level39',
 'first_utm_medium_c_Level4',
 'first_utm_medium_c_Level40',
 'first_utm_medium_c_Level41',
 'first_utm_medium_c_Level42',
 'first_utm_medium_c_Level43',
 'first_utm_medium_c_Level44',
 'first_utm_medium_c_Level5',
 'first_utm_medium_c_Level6',
 'first_utm_medium_c_Level7',
 'first_utm_medium_c_Level8',
 'first_utm_medium_c_Level9',
 'first_utm_source_c_Level0',
 'first_utm_source_c_Level14',
 'first_utm_source_c_Level16',
 'first_utm_source_c_Level2',
 'first_utm_source_c_Level4',
 'first_utm_source_c_Level5',
 'first_utm_source_c_Level6',
 'first_utm_source_c_Level7',
 'first_utm_source_c_others',
 'referred_lead_1.0']

In [ ]:
%matplotlib inline

In [ ]:
plot_model(lgbm, plot = 'auc')

In [ ]:
plot_model(lgbm, plot = 'pr')

In [ ]:
plot_model(lgbm, plot = 'confusion_matrix', plot_kwargs = {'percent' : True})

In [ ]:
# create feature importance plot
plot_model(lgbm, plot='feature')

### 5 : Model Experimentation after dropping features

From the above feature tests we can claerly see that some of the features are not significant. We will now drop all the insignificant features and select only the significant ones.
The list of the significant features is 
['total_leads_droppped', 'city_tier', 'referred_lead', 'app_complete_flag', 'first_platform_c', 'first_utm_medium_c', 'first_utm_source_c'].
So now you will train your model with onlly these features.

Also note that in our previous experiments we saw that tree based models are our top performers. In case of tree based models we do not require transformationss normalization, scaling etc. So make sure that you use setup pycaret in the proper way. i.e, make sure that you use normalize = False and transformation = False.

In [73]:
# 
# ['total_leads_droppped', 'city_tier', 'referred_lead', 'app_complete_flag', 'first_platform_c', 'first_utm_medium_c', 'first_utm_source_c']
#
# Train the model using the features listed above. Since we are using tree models we do not require any transformaions 
# such as normalization, scaling etc.So make sure that you use setup pycaret in the proper way. i.e, make sure that you use 
# normalize = False and transformation = False.
selected_features = ['total_leads_droppped', 'city_tier', 'referred_lead',
                     'first_platform_c', 'first_utm_medium_c', 'first_utm_source_c','app_complete_flag']

training_model = data_for_model[selected_features]

Lead_scoring_mlflow_production = setup(data = training_model, target = 'app_complete_flag', 
                   session_id = 42,fix_imbalance=False,
                   n_jobs=-1,use_gpu=True,normalize=False,transformation=False,
                   log_experiment=True,experiment_name='Lead_scoring_mlflow_production',
                   log_plots=True, log_data=True,
                   silent=True, verbose=True,
                   log_profile=False)

In [74]:
# create a experimentation with pycaret and exclude ['gbc','knn','qda', 'dummy', 'svm', 'ada']. 
excluded_models = ['gbc', 'knn', 'qda', 'dummy', 'svm', 'ada']
best_model = compare_models(fold = 5, exclude=excluded_models)

In [75]:
# You should get lightgbm as the best performing model. So now we will train a lightGBM model manually using pycaret

lgbm_post_feature_removal  = create_model('lightgbm', fold = 5)

In [76]:
#Faced multiple issues with optuna, as suggested by mentor, we are using scikit-optimize
lgbm_post_feature_removal.feature_name_

['total_leads_droppped',
 'city_tier',
 'referred_lead_0.0',
 'first_platform_c_Level0',
 'first_platform_c_Level1',
 'first_platform_c_Level10',
 'first_platform_c_Level12',
 'first_platform_c_Level13',
 'first_platform_c_Level14',
 'first_platform_c_Level15',
 'first_platform_c_Level17',
 'first_platform_c_Level18',
 'first_platform_c_Level19',
 'first_platform_c_Level2',
 'first_platform_c_Level20',
 'first_platform_c_Level21',
 'first_platform_c_Level22',
 'first_platform_c_Level23',
 'first_platform_c_Level24',
 'first_platform_c_Level25',
 'first_platform_c_Level26',
 'first_platform_c_Level27',
 'first_platform_c_Level28',
 'first_platform_c_Level29',
 'first_platform_c_Level3',
 'first_platform_c_Level30',
 'first_platform_c_Level31',
 'first_platform_c_Level32',
 'first_platform_c_Level33',
 'first_platform_c_Level34',
 'first_platform_c_Level35',
 'first_platform_c_Level36',
 'first_platform_c_Level37',
 'first_platform_c_Level38',
 'first_platform_c_Level39',
 'first_platform_c_Level4',
 'first_platform_c_Level40',
 'first_platform_c_Level41',
 'first_platform_c_Level45',
 'first_platform_c_Level46',
 'first_platform_c_Level47',
 'first_platform_c_Level5',
 'first_platform_c_Level6',
 'first_platform_c_Level7',
 'first_platform_c_Level8',
 'first_platform_c_Level9',
 'first_utm_medium_c_Level0',
 'first_utm_medium_c_Level1',
 'first_utm_medium_c_Level10',
 'first_utm_medium_c_Level11',
 'first_utm_medium_c_Level12',
 'first_utm_medium_c_Level13',
 'first_utm_medium_c_Level14',
 'first_utm_medium_c_Level15',
 'first_utm_medium_c_Level16',
 'first_utm_medium_c_Level17',
 'first_utm_medium_c_Level18',
 'first_utm_medium_c_Level19',
 'first_utm_medium_c_Level2',
 'first_utm_medium_c_Level20',
 'first_utm_medium_c_Level21',
 'first_utm_medium_c_Level22',
 'first_utm_medium_c_Level23',
 'first_utm_medium_c_Level24',
 'first_utm_medium_c_Level25',
 'first_utm_medium_c_Level26',
 'first_utm_medium_c_Level27',
 'first_utm_medium_c_Level28',
 'first_utm_medium_c_Level29',
 'first_utm_medium_c_Level3',
 'first_utm_medium_c_Level30',
 'first_utm_medium_c_Level31',
 'first_utm_medium_c_Level32',
 'first_utm_medium_c_Level33',
 'first_utm_medium_c_Level34',
 'first_utm_medium_c_Level35',
 'first_utm_medium_c_Level36',
 'first_utm_medium_c_Level37',
 'first_utm_medium_c_Level38',
 'first_utm_medium_c_Level39',
 'first_utm_medium_c_Level4',
 'first_utm_medium_c_Level40',
 'first_utm_medium_c_Level41',
 'first_utm_medium_c_Level42',
 'first_utm_medium_c_Level43',
 'first_utm_medium_c_Level44',
 'first_utm_medium_c_Level5',
 'first_utm_medium_c_Level6',
 'first_utm_medium_c_Level7',
 'first_utm_medium_c_Level8',
 'first_utm_medium_c_Level9',
 'first_utm_source_c_Level0',
 'first_utm_source_c_Level14',
 'first_utm_source_c_Level16',
 'first_utm_source_c_Level2',
 'first_utm_source_c_Level4',
 'first_utm_source_c_Level5',
 'first_utm_source_c_Level6',
 'first_utm_source_c_Level7',
 'first_utm_source_c_others']

In [ ]:
#pip install optuna

In [77]:
pip install scikit-optimize

Requirement already satisfied: scikit-optimize in /opt/conda/lib/python3.8/site-packages (0.9.0)
Requirement already satisfied: scipy>=0.19.1 in /opt/conda/lib/python3.8/site-packages (from scikit-optimize) (1.5.3)
Requirement already satisfied: numpy>=1.13.3 in /opt/conda/lib/python3.8/site-packages (from scikit-optimize) (1.22.2)
Requirement already satisfied: scikit-learn>=0.20.0 in /opt/conda/lib/python3.8/site-packages (from scikit-optimize) (0.24.0)
Requirement already satisfied: pyaml>=16.9 in /opt/conda/lib/python3.8/site-packages (from scikit-optimize) (21.10.1)
Requirement already satisfied: joblib>=0.11 in /opt/conda/lib/python3.8/site-packages (from scikit-optimize) (1.1.0)
Requirement already satisfied: PyYAML in /opt/conda/lib/python3.8/site-packages (from pyaml>=16.9->scikit-optimize) (6.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /opt/conda/lib/python3.8/site-packages (from scikit-learn>=0.20.0->scikit-optimize) (3.1.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Note: you may need to restart the kernel to use updated packages.

# Tune the hyper parameters of the lightgbm model using optuna on 10 folds and optimise AUC as that was our system metric, 
# hence we will optimise AUC
#tuned_lgbm_optuna,tuner_1 = tune_model(lgbm_post_feature_removal, 
                                    search_library='optuna',
                                    search_algorithm='tpe',
                                    fold = 10,
                                    optimize = 'AUC',
                                    choose_better=True,
                                    return_tuner=True)

In [78]:
# Tune the hyper parameters of the lightgbm model using optuna on 10 folds and optimise AUC as that was our system metric, 
# Optuna is giving error, hence we will optimise AUC as suggested by mentor
tuned_lgbm_optuna,tuner_1 = tune_model(lgbm_post_feature_removal, 
                                    search_library='scikit-optimize',
                                    fold = 10,
                                    optimize = 'AUC',
                                    choose_better=True,
                                    return_tuner=True)

In [79]:
# Print the final models configuration so that we can use it in the model retraining pipeline 
print(tuner_1)

BayesSearchCV(cv=StratifiedKFold(n_splits=10, random_state=None, shuffle=False),
              error_score='raise',
              estimator=Pipeline(memory=None,
                                 steps=[('empty_step', 'passthrough'),
                                        ('actual_estimator',
                                         LGBMClassifier(boosting_type='gbdt',
                                                        class_weight=None,
                                                        colsample_bytree=1.0,
                                                        device='gpu',
                                                        importance_type='split',
                                                        learning_rate=0.1,
                                                        max_depth=-1,
                                                        min_child_samples=20,
                                                        m...
                             'actual_estimator__n_estimators': Integer(low=10, high=300, prior='uniform', transform='normalize'),
                             'actual_estimator__num_leaves': Integer(low=2, high=256, prior='uniform', transform='normalize'),
                             'actual_estimator__reg_alpha': Real(low=1e-10, high=10, prior='log-uniform', transform='normalize'),
                             'actual_estimator__reg_lambda': Real(low=1e-10, high=10, prior='log-uniform', transform='normalize')},
              verbose=1)

In [80]:
pipeline = get_config(variable="prep_pipe")
pipeline

Pipeline(memory=None,
         steps=[('dtypes',
                 DataTypes_Auto_infer(categorical_features=[],
                                      display_types=False, features_todrop=[],
                                      id_columns=[],
                                      ml_usecase='classification',
                                      numerical_features=[],
                                      target='app_complete_flag',
                                      time_features=[])),
                ('imputer',
                 Simple_Imputer(categorical_strategy='not_available',
                                fill_value_categorical=None,
                                fill_value_numerical=None,
                                n...
                ('scaling', 'passthrough'), ('P_transform', 'passthrough'),
                ('binn', 'passthrough'), ('rem_outliers', 'passthrough'),
                ('cluster_all', 'passthrough'),
                ('dummy', Dummify(target='app_complete_flag')),
                ('fix_perfect', Remove_100(target='app_complete_flag')),
                ('clean_names', Clean_Colum_Names()),
                ('feature_select', 'passthrough'), ('fix_multi', 'passthrough'),
                ('dfs', 'passthrough'), ('pca', 'passthrough')],
         verbose=False)

In [81]:
tuned_lgbm_optuna.feature_name_

['total_leads_droppped',
 'city_tier',
 'referred_lead_0.0',
 'first_platform_c_Level0',
 'first_platform_c_Level1',
 'first_platform_c_Level10',
 'first_platform_c_Level12',
 'first_platform_c_Level13',
 'first_platform_c_Level14',
 'first_platform_c_Level15',
 'first_platform_c_Level17',
 'first_platform_c_Level18',
 'first_platform_c_Level19',
 'first_platform_c_Level2',
 'first_platform_c_Level20',
 'first_platform_c_Level21',
 'first_platform_c_Level22',
 'first_platform_c_Level23',
 'first_platform_c_Level24',
 'first_platform_c_Level25',
 'first_platform_c_Level26',
 'first_platform_c_Level27',
 'first_platform_c_Level28',
 'first_platform_c_Level29',
 'first_platform_c_Level3',
 'first_platform_c_Level30',
 'first_platform_c_Level31',
 'first_platform_c_Level32',
 'first_platform_c_Level33',
 'first_platform_c_Level34',
 'first_platform_c_Level35',
 'first_platform_c_Level36',
 'first_platform_c_Level37',
 'first_platform_c_Level38',
 'first_platform_c_Level39',
 'first_platform_c_Level4',
 'first_platform_c_Level40',
 'first_platform_c_Level41',
 'first_platform_c_Level45',
 'first_platform_c_Level46',
 'first_platform_c_Level47',
 'first_platform_c_Level5',
 'first_platform_c_Level6',
 'first_platform_c_Level7',
 'first_platform_c_Level8',
 'first_platform_c_Level9',
 'first_utm_medium_c_Level0',
 'first_utm_medium_c_Level1',
 'first_utm_medium_c_Level10',
 'first_utm_medium_c_Level11',
 'first_utm_medium_c_Level12',
 'first_utm_medium_c_Level13',
 'first_utm_medium_c_Level14',
 'first_utm_medium_c_Level15',
 'first_utm_medium_c_Level16',
 'first_utm_medium_c_Level17',
 'first_utm_medium_c_Level18',
 'first_utm_medium_c_Level19',
 'first_utm_medium_c_Level2',
 'first_utm_medium_c_Level20',
 'first_utm_medium_c_Level21',
 'first_utm_medium_c_Level22',
 'first_utm_medium_c_Level23',
 'first_utm_medium_c_Level24',
 'first_utm_medium_c_Level25',
 'first_utm_medium_c_Level26',
 'first_utm_medium_c_Level27',
 'first_utm_medium_c_Level28',
 'first_utm_medium_c_Level29',
 'first_utm_medium_c_Level3',
 'first_utm_medium_c_Level30',
 'first_utm_medium_c_Level31',
 'first_utm_medium_c_Level32',
 'first_utm_medium_c_Level33',
 'first_utm_medium_c_Level34',
 'first_utm_medium_c_Level35',
 'first_utm_medium_c_Level36',
 'first_utm_medium_c_Level37',
 'first_utm_medium_c_Level38',
 'first_utm_medium_c_Level39',
 'first_utm_medium_c_Level4',
 'first_utm_medium_c_Level40',
 'first_utm_medium_c_Level41',
 'first_utm_medium_c_Level42',
 'first_utm_medium_c_Level43',
 'first_utm_medium_c_Level44',
 'first_utm_medium_c_Level5',
 'first_utm_medium_c_Level6',
 'first_utm_medium_c_Level7',
 'first_utm_medium_c_Level8',
 'first_utm_medium_c_Level9',
 'first_utm_source_c_Level0',
 'first_utm_source_c_Level14',
 'first_utm_source_c_Level16',
 'first_utm_source_c_Level2',
 'first_utm_source_c_Level4',
 'first_utm_source_c_Level5',
 'first_utm_source_c_Level6',
 'first_utm_source_c_Level7',
 'first_utm_source_c_others']